### ISSUE TITLE
Release 0.3.3

### ISSUE THREAD

**Issue by Baril27** [jhilden/i18n_viz#14]
Great work on this gem really appreciate it! Made my team super happy dealing with translations. One issue I currently have is currently fixed on master (commit 1b5b020) but there is no release for it. Can you please add a release for version 0.3.3. I currently have to fork the repo since I don't want to just point to master incase there are anymore changes going forward. Thank you again.

**Comment by jhilden** [comment]
I just released the current master as version `0.4.0`.  I hope that works for you.

If you could take a quick look at the changelog and see if you know of any additional things that should be added for version `0.4.0` that would be super nice.
